# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "experiments", :force => true do |t|
    t.string   "name"
    t.text     "description"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "members", :force => true do |t|
    t.string   "name"
    t.integer  "membership_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "supervisor_id"
  end

  create_table "memberships", :force => true do |t|
    t.integer  "member_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "project_id"
    t.string   "project_type"
  end

  create_table "supervisors", :force => true do |t|
    t.string   "name"
    t.string   "title"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "members_count"
  end

  create_table "trials", :force => true do |t|
    t.string   "name"
    t.decimal  "hours"
    t.text     "description"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "membership_id"
  end

end
